---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/diremidloreto/public_html/ici.diremidloreto.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/diremidloreto/web_ici/
      - /bin/rsync -av ./ $DEPLOYPATH

