---
  deployment:
    tasks:
      - export DEPLOYPATH=/home/soportediremidlo/public_html/ici.soportediremidloreto.com/
      - /bin/rsync -av public/ $DEPLOYPATH
      - export DEPLOYPATH=/home/soportediremidlo/web_ici/
      - /bin/rsync -av ./ $DEPLOYPATH

