<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Ime1 extends Model
{
    protected $table = 'ime1';

    protected $fillable = [
        'ANNOMES',
        'CODIGO_EJE',
        'CODIGO_PRE',
        'IMPVTAS',
        'IMPCREDH',
        'IMPSOAT',
        'IMPOTRC',
        'IMPSIS',
        'IMPINTS',
        'IMPDN',
        'IMPEXO',
        'DVTAS80',
        'DVTAS20',
        'DCREH80',
        'DCREH20',
        'DSOAT80',
        'DSOAT20',
        'DOTRC80',
        'DOTRC20',
        'TOTRDR',
        'DSIS80',
        'DSIS20',
        'DINTSAN80',
        'DINTSAN20',
        'DDN80',
        'DDN20',
        'CTCREDH',
        'CTSOAT',
        'CTOCONV',
        'CTSIS',
        'CTISAN',
        'CTDN',
        'SALMEDA',
        'FORT110',
        'EXO1',
        'ABMEDIN',
        'SMEDSIG',
        'SADMA',
        'FORT010',
        'EXO0',
        'GASTADM',
        'SADMSIG',
        'BVTASER1',
        'BVTADEL1',
        'BVTAAL1',
        'BVTAAN1',
        'BVTASER2',
        'BVTADEL2',
        'BVTAAL2',
        'BVTAAN2',
        'BVTASER3',
        'BVTADEL3',
        'BVTAAL3',
        'BVTAAN3',
        'FACTSER',
        'FACTDEL',
        'FACTAL',
        'FACTAN',
        'IMPBVVTA',
        'IMPBVSIS',
        'IMPBVEXO',
        'IMPBVSOAT',
        'IMPBVOCONV',
        'IMPBVINTSA',
        'IMPBVDN',
        'FECHREG',
        'FECHULTM',
        'USUARIO',
    ];
}
